import { ScamReport } from './dynamodb'

export const MOCK_REPORTS: ScamReport[] = [
  {
    id: 'mock-001',
    scamType: 'Phishing Email',
    platform: 'Email',
    description: 'Received a fake bank email asking to verify account details. The email looked very convincing with official bank logos.',
    financialLoss: 2500,
    currency: 'MYR',
    victimAge: '35-44',
    reportedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    severity: 'high',
    status: 'verified',
    contactMethod: 'Email',
    region: 'Kuala Lumpur',
    anonymous: false,
  },
  {
    id: 'mock-002',
    scamType: 'Fake Job Offer',
    platform: 'Telegram',
    description: 'Got offered a remote data entry job paying RM5000/month. Asked to pay RM300 registration fee first. Never heard back.',
    financialLoss: 300,
    currency: 'MYR',
    victimAge: '18-24',
    reportedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    severity: 'medium',
    status: 'verified',
    contactMethod: 'Telegram',
    region: 'Selangor',
    anonymous: true,
  },
  {
    id: 'mock-003',
    scamType: 'Investment Fraud',
    platform: 'WhatsApp',
    description: 'Invited into a WhatsApp investment group promising 30% returns monthly. Lost entire savings after they disappeared.',
    financialLoss: 45000,
    currency: 'MYR',
    victimAge: '45-54',
    reportedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    severity: 'high',
    status: 'investigating',
    contactMethod: 'WhatsApp',
    region: 'Penang',
    anonymous: false,
  },
  {
    id: 'mock-004',
    scamType: 'Romance Scam',
    platform: 'Facebook',
    description: 'Met someone on Facebook who claimed to be a doctor working overseas. After months of chatting, asked for money for a flight home.',
    financialLoss: 8000,
    currency: 'MYR',
    victimAge: '55-64',
    reportedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    severity: 'high',
    status: 'verified',
    contactMethod: 'Facebook Messenger',
    region: 'Johor Bahru',
    anonymous: true,
  },
  {
    id: 'mock-005',
    scamType: 'Online Shopping Fraud',
    platform: 'Instagram',
    description: 'Ordered branded goods from an Instagram shop. Paid via bank transfer, items never arrived.',
    financialLoss: 650,
    currency: 'MYR',
    victimAge: '25-34',
    reportedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    severity: 'medium',
    status: 'pending',
    contactMethod: 'Instagram DM',
    region: 'Kota Kinabalu',
    anonymous: false,
  },
  {
    id: 'mock-006',
    scamType: 'Tech Support Scam',
    platform: 'Phone Call',
    description: 'Received a call claiming to be from Microsoft saying my computer was hacked. They asked for remote access and payment.',
    financialLoss: 1200,
    currency: 'MYR',
    victimAge: '65+',
    reportedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    severity: 'high',
    status: 'verified',
    contactMethod: 'Phone',
    region: 'Ipoh',
    anonymous: false,
  },
  {
    id: 'mock-007',
    scamType: 'Cryptocurrency Scam',
    platform: 'Telegram',
    description: 'Joined a crypto trading group with a "guru" showing fake profits. Invested and the platform disappeared overnight.',
    financialLoss: 15000,
    currency: 'MYR',
    victimAge: '25-34',
    reportedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    severity: 'high',
    status: 'investigating',
    contactMethod: 'Telegram',
    region: 'Kuala Lumpur',
    anonymous: true,
  },
  {
    id: 'mock-008',
    scamType: 'SMS/WhatsApp Scam',
    platform: 'SMS',
    description: 'Received SMS claiming parcel held at customs. Clicked link and entered banking details on fake website.',
    financialLoss: 3400,
    currency: 'MYR',
    victimAge: '35-44',
    reportedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    severity: 'high',
    status: 'verified',
    contactMethod: 'SMS',
    region: 'Shah Alam',
    anonymous: false,
  },
]

export const MOCK_STATS = {
  totalReports: 1847,
  totalLoss: 2340000,
  reportedThisWeek: 142,
  averageLoss: 6800,
  topScamType: 'Investment Fraud',
  resolvedCases: 432,
  scamTypeBreakdown: [
    { type: 'Investment Fraud', count: 312, percentage: 22.4 },
    { type: 'Phishing Email', count: 287, percentage: 20.6 },
    { type: 'Online Shopping', count: 198, percentage: 14.2 },
    { type: 'Fake Job Offer', count: 176, percentage: 12.6 },
    { type: 'Romance Scam', count: 142, percentage: 10.2 },
    { type: 'Cryptocurrency', count: 128, percentage: 9.2 },
    { type: 'Tech Support', count: 94, percentage: 6.7 },
    { type: 'Other', count: 56, percentage: 4.0 },
  ],
  monthlyTrend: [
    { month: 'Aug', reports: 124, loss: 168000 },
    { month: 'Sep', reports: 138, loss: 192000 },
    { month: 'Oct', reports: 156, loss: 215000 },
    { month: 'Nov', reports: 171, loss: 244000 },
    { month: 'Dec', reports: 189, loss: 278000 },
    { month: 'Jan', reports: 203, loss: 301000 },
    { month: 'Feb', reports: 217, loss: 342000 },
  ],
  platformBreakdown: [
    { platform: 'WhatsApp', count: 487, percentage: 35.2 },
    { platform: 'Facebook', count: 312, percentage: 22.5 },
    { platform: 'Email', count: 234, percentage: 16.9 },
    { platform: 'Telegram', count: 198, percentage: 14.3 },
    { platform: 'Instagram', count: 87, percentage: 6.3 },
    { platform: 'Phone/SMS', count: 67, percentage: 4.8 },
  ],
  ageBreakdown: [
    { group: '18-24', percentage: 12 },
    { group: '25-34', percentage: 24 },
    { group: '35-44', percentage: 22 },
    { group: '45-54', percentage: 19 },
    { group: '55-64', percentage: 15 },
    { group: '65+', percentage: 8 },
  ],
}
